spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  cache:
    type: redis
    redis:
      host: ${REDIS_URL}
      port: 13949
      password: ${REDIS_PASSWORD}
    mail:
      host: smtp.mailtrap.io
      port: 2525
      username: xknzodekqkif
      password: kxtnmdmkejsg
      properties:
        mail:
          transport:
            protocol: smtp
          debug: true
          smtp:
            auth: true
            starttls:
              enable: true
jwt:
  secret: secreto